services:
  - type: web
    name: portfolio-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_backend.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio_backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
